version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: dev
  labels:
  - dependencies
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
    - 7.13.15
  - dependency-name: mongoose
    versions:
    - 5.11.20
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.16
