version: 2.1
jobs:
  build:
    working_directory: ~/testing
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-cache-{{ checksum "yarn.lock" }}
            - v1-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-cache-{{ checksum "yarn.lock" }}

      - run: yarn test
