"""Update transaction foreign keys

Revision ID: 11d0250598ee
Revises: a14a88a4c16a
Create Date: 2022-01-23 19:50:57.748485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "11d0250598ee"
down_revision = "a14a88a4c16a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("from_account_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("to_account_id", postgresql.UUID(as_uuid=True), nullable=True),
    )
    op.drop_constraint(
        "fk_transactions_from_account_accounts", "transactions", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_transactions_to_account_accounts", "transactions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_transactions_to_account_id_accounts"),
        "transactions",
        "accounts",
        ["to_account_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_transactions_from_account_id_accounts"),
        "transactions",
        "accounts",
        ["from_account_id"],
        ["id"],
    )
    op.drop_column("transactions", "from_account")
    op.drop_column("transactions", "to_account")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("to_account", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "from_account", postgresql.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        op.f("fk_transactions_from_account_id_accounts"),
        "transactions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_transactions_to_account_id_accounts"),
        "transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_transactions_to_account_accounts",
        "transactions",
        "accounts",
        ["to_account"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_transactions_from_account_accounts",
        "transactions",
        "accounts",
        ["from_account"],
        ["id"],
    )
    op.drop_column("transactions", "to_account_id")
    op.drop_column("transactions", "from_account_id")
    # ### end Alembic commands ###
