"""Add callback_url for applications

Revision ID: 2e0ace032da5
Revises: 11d0250598ee
Create Date: 2022-01-23 20:50:35.609920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0ace032da5'
down_revision = '11d0250598ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_applications', sa.Column('callback_url', sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_applications', 'callback_url')
    # ### end Alembic commands ###
