"""Add relations between Account and ExternalApplication, rename enum EndpointPermissions to Permissions

Revision ID: 5dace0059485
Revises: ab940370fa85
Create Date: 2022-01-13 09:34:26.139784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dace0059485'
down_revision = 'ab940370fa85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('application_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'external_applications', ['application_id'], ['id'])
    op.add_column('transactions', sa.Column('application_id', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_application_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'external_applications', ['application_id'], ['id'])
    op.drop_column('transactions', 'application')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('application', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_application_fkey', 'transactions', 'external_applications', ['application'], ['id'])
    op.drop_column('transactions', 'application_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'application_id')
    # ### end Alembic commands ###
    op.execute('DROP TYPE permissions')
