"""Add application_id to Account

Revision ID: f7c61cd99317
Revises: ab940370fa85
Create Date: 2022-01-20 13:42:10.056457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "f7c61cd99317"
down_revision = "ab940370fa85"
branch_labels = None
depends_on = None

old_type = postgresql.ENUM(
    "ExternalApplications", "Transactions", name="endpointpermissions"
)
new_type = postgresql.ENUM("Transactions", "UserToUserTransactions", name="permissions")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("application_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_accounts_application_id_external_applications"),
        "accounts",
        "external_applications",
        ["application_id"],
        ["id"],
    )
    op.add_column(
        "transactions", sa.Column("application_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "fk_transactions_application_external_applications",
        "transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_transactions_application_id_external_applications"),
        "transactions",
        "external_applications",
        ["application_id"],
        ["id"],
    )
    op.drop_column("transactions", "application")
    # ### end Alembic commands ###
    new_type.create(op.get_bind(), checkfirst=False)

    op.execute(
        "ALTER TABLE external_applications ALTER COLUMN permissions TYPE permissions[] USING permissions::text::permissions[]"
    )

    old_type.drop(op.get_bind(), checkfirst=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("application", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("fk_transactions_application_id_external_applications"),
        "transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_transactions_application_external_applications",
        "transactions",
        "external_applications",
        ["application"],
        ["id"],
    )
    op.drop_column("transactions", "application_id")
    op.drop_constraint(
        op.f("fk_accounts_application_id_external_applications"),
        "accounts",
        type_="foreignkey",
    )
    op.drop_column("accounts", "application_id")
    # ### end Alembic commands ###
    old_type.create(op.get_bind(), checkfirst=False)

    op.execute(
        "ALTER TABLE external_applications ALTER COLUMN permissions TYPE endpointpermissions[] USING permissions::text::endpointpermissions[]"
    )

    new_type.drop(op.get_bind(), checkfirst=False)
